# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Universal' do
    pod 'Alamofire', '~> 4.5'
    pod 'SwiftyJSON'
	pod 'Fusuma'

  end
